 CREATE TABLE [dbComputadores].[Stage].[StgComputadores]
 (
	 [Marka] VARCHAR(MAX)
	,[Fiyat] VARCHAR(MAX)
	,[İşlemci Tipi] VARCHAR(MAX)
	,[SSD Kapasitesi] VARCHAR(MAX)
	,[Ram (Sistem Belleği)] VARCHAR(MAX)
	,[Ekran Kartı] VARCHAR(MAX)
	,[Kapasite] VARCHAR(MAX)
	,[İşletim Sistemi] VARCHAR(MAX)
	,[Ekran Kartı Bellek Tipi] VARCHAR(MAX)
	,[Ekran Kartı Tipi] VARCHAR(MAX)
	,[Garanti Tipi] VARCHAR(MAX)
	,[Ram (Sistem Belleği) Tipi] VARCHAR(MAX)
	,[İşlemci Çekirdek Sayısı] VARCHAR(MAX)
	,[İşlemci Nesli] VARCHAR(MAX)
	,[İşlemci Modeli] VARCHAR(MAX)
	,[Çözünürlük] VARCHAR(MAX)
	,[Power Supply] VARCHAR(MAX)
	,[Kullanım Amacı] VARCHAR(MAX)
	,[Ekran Kartı Hafızası] VARCHAR(MAX)
	,[Temel İşlemci Hızı (GHz)] VARCHAR(MAX)
	,[Bağlantılar] VARCHAR(MAX)
	,[Cihaz Ağırlığı] VARCHAR(MAX)
	,[Ekran Boyutu] VARCHAR(MAX)
	,[İşlemci Frekansı] VARCHAR(MAX)
	,[Ekran Yenileme Hızı] VARCHAR(MAX)
	,[Panel Tipi] VARCHAR(MAX)
	,[Menşei] VARCHAR(MAX)
	,[Arttırılabilir Azami Bellek] VARCHAR(MAX)
)